#!/usr/bin/env bash
#
# AI Job Hunter - Oracle Cloud Always Free VPS bootstrap.
#
# Usage (run on the server as root):
#   sudo bash deploy/oracle/setup.sh            # plain HTTP on the public IP
#   sudo bash deploy/oracle/setup.sh jobs.my.com  # domain with automatic HTTPS
#
# What it does:
#   1. Installs Python, Caddy, Playwright Chromium
#   2. Copies the repo to /opt/ai-job-hunter (or clones it from GitHub)
#   3. Creates a dedicated 'jobhunter' service user + venv + .env
#   4. Installs a systemd unit (starts the scheduler via gunicorn.conf.py)
#   5. Configures Caddy reverse proxy and UFW firewall
#
# Prerequisites (done in the Oracle Console):
#   - Always Free VM, Ubuntu 24.04 (Ampere A1 ARM recommended over the
#     1GB-RAM AMD shape so Chromium does not OOM)
#   - VCN Security List: open TCP 22, 80, 443
#   - Your SSH public key added to the instance
set -euo pipefail

DOMAIN="${1:-}"

APP_DIR="/opt/ai-job-hunter"
SERVICE_USER="jobhunter"
REPO_URL="${REPO_URL:-https://github.com/sleepyrisu/job-hunter.git}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run as root:  sudo bash deploy/oracle/setup.sh $*"
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "==> Updating system packages"
apt-get update -y
apt-get upgrade -y
apt-get install -y python3 python3-venv python3-pip git curl rsync ufw gpg ca-certificates

echo "==> Installing Caddy web server"
curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
  | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] \
https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt" > /etc/apt/sources.list.d/caddy-stable.list
apt-get update -y
apt-get install -y caddy

echo "==> Creating service user '$SERVICE_USER'"
if ! id "$SERVICE_USER" >/dev/null 2>&1; then
  useradd -m -s /bin/bash "$SERVICE_USER"
fi

echo "==> Copying application code to $APP_DIR"
if [[ -f "$SCRIPT_DIR/../../app.py" ]]; then
  # Running from inside the repo (e.g. scp'd up): copy it in place.
  # Trailing slash copies the contents, not a nested folder.
  mkdir -p "$APP_DIR"
  rsync -a --delete "$SCRIPT_DIR/../../" "$APP_DIR/" \
    --exclude .git --exclude .venv --exclude __pycache__ --exclude .env
else
  # Fall back to cloning from GitHub.
  git clone "$REPO_URL" "$APP_DIR"
fi
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIR"

# su without "-" keeps root's HOME, so Playwright browsers would land in
# /root/.cache and be unreadable by the service user. Fix HOME explicitly.
echo "==> Creating Python virtualenv + installing dependencies"
su -s /bin/bash "$SERVICE_USER" -c \
  "export HOME=/home/$SERVICE_USER && cd $APP_DIR && python3 -m venv .venv && .venv/bin/pip install --upgrade pip && .venv/bin/pip install -r requirements.txt"

echo "==> Installing Chromium for Playwright"
"$APP_DIR/.venv/bin/python" -m playwright install-deps chromium
su -s /bin/bash "$SERVICE_USER" -c \
  "export HOME=/home/$SERVICE_USER && cd $APP_DIR && .venv/bin/python -m playwright install chromium"

echo "==> Creating .env (edit it to add your API keys)"
ENV_FILE="$APP_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  {
    echo "# Generated by deploy/oracle/setup.sh on $(date -u)"
    echo "SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    echo "DASHBOARD_TOKEN=$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
    echo ""
    echo "# --- AI Provider (choose one) ---"
    echo "AGNES_API_KEY="
    echo "AGNES_BASE_URL=https://apihub.agnes-ai.com/v1"
    echo "GEMINI_API_KEY="
    echo ""
    echo "# --- Search Settings ---"
    echo "# SEARCH_KEYWORDS=\"Data Analyst,RPA Developer,Python Developer\""
    echo "# LOCATIONS=\"Penang, Malaysia,Kuala Lumpur, Malaysia\""
    echo "# MATCH_THRESHOLD=80"
    echo ""
    echo "# --- Email Notifications (optional) ---"
    echo "# EMAIL_SENDER=you@gmail.com"
    echo "# EMAIL_PASSWORD=your_app_password"
    echo "# EMAIL_RECEIVER=dest@example.com"
    echo ""
    echo "# --- Telegram Notifications (optional) ---"
    echo "# TELEGRAM_BOT_TOKEN=bot123456:ABC-DEF..."
    echo "# TELEGRAM_CHAT_ID=123456789"
  } > "$ENV_FILE"
fi
chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"

echo "==> Installing systemd service"
cp "$SCRIPT_DIR/ai-job-hunter.service" /etc/systemd/system/ai-job-hunter.service
systemctl daemon-reload
systemctl enable ai-job-hunter
systemctl restart ai-job-hunter

echo "==> Configuring Caddy reverse proxy"
SERVER_IP="$(hostname -I | awk '{print $1}')"
if [[ -n "$DOMAIN" ]]; then
  SITE="$DOMAIN"
else
  SITE=":80"
fi
cat > /etc/caddy/Caddyfile <<EOF
$SITE {
    reverse_proxy 127.0.0.1:8888
}
EOF
systemctl restart caddy

echo "==> Configuring firewall"
ufw allow OpenSSH >/dev/null
ufw allow 80/tcp >/dev/null
ufw allow 443/tcp >/dev/null
ufw --force enable >/dev/null

echo ""
echo "======================================================"
echo " Done!"
echo ""
echo " Dashboard URL:  http://$SERVER_IP  (or https://$DOMAIN)"
echo " Dashboard token: $(grep '^DASHBOARD_TOKEN=' "$ENV_FILE" | cut -d= -f2)"
echo ""
echo " Next steps:"
echo "   1) nano $ENV_FILE  -> add your API keys, then:"
echo "      sudo systemctl restart ai-job-hunter"
echo "   2) View logs:  sudo journalctl -u ai-job-hunter -f"
echo "======================================================"
